# Generated by Django 3.1.7 on 2021-03-14 14:53

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invalid_trigger', models.CharField(default='', max_length=70)),
                ('key', models.CharField(default='', max_length=70)),
                ('name', models.CharField(default='', max_length=70)),
                ('reuse', models.BooleanField(default=False)),
                ('pick_first', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('supported_values', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('types', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('validation_parser', models.CharField(default='', max_length=70)),
                ('values', models.JSONField()),
            ],
        ),
    ]
